
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Tauri command: get the application version.
 */
async getAppVersion() : Promise<string> {
    return await TAURI_INVOKE("get_app_version");
},
/**
 * Tauri command: check if the MCP server is running.
 */
async isMcpRunning() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_mcp_running") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a vault at the given path, start the file watcher, and return the file listing.
 */
async openVault(path: string) : Promise<Result<VaultFile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_vault", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all files in the currently open vault.
 */
async listFiles() : Promise<Result<VaultFile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a note from the vault and return its content with parsed frontmatter.
 */
async readNote(path: string) : Promise<Result<NoteData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_note", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write content to a note in the vault (atomic write).
 */
async writeNote(path: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_note", { path, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new note with the given title and optional folder.
 * Returns the relative path of the created note.
 */
async createNote(title: string, folder: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_note", { title, folder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename (move) a note from one path to another.
 */
async renameNote(oldPath: string, newPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_note", { oldPath, newPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a note by its relative path.
 */
async deleteNote(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_note", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a folder inside the vault.
 */
async createFolder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save a note and emit a "note-saved" event to the frontend.
 */
async saveNote(path: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_note", { path, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Full-text search across all indexed notes in the vault.
 * 
 * Returns up to `limit` results (default 20) ranked by relevance.
 */
async fullTextSearch(query: string, limit: number | null) : Promise<Result<SearchResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("full_text_search", { query, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rebuild the full search index from all vault files.
 */
async rebuildSearchIndex() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rebuild_search_index") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all backlinks for a given note.
 */
async getBacklinks(notePath: string) : Promise<Result<Backlink[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_backlinks", { notePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get graph data for visualization.
 * 
 * If `center` is provided, returns a subgraph centered on that note up to `depth` hops.
 * If `center` is `None`, returns the full graph.
 */
async getGraphData(center: string | null, depth: number) : Promise<Result<GraphData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_graph_data", { center, depth }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all tags in the vault with their occurrence counts.
 */
async getAllTags() : Promise<Result<TagInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_tags") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all note paths that have a specific tag.
 */
async getNotesByTag(tag: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_notes_by_tag", { tag }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create or open today's daily note. Returns the relative path inside the vault.
 */
async createDailyNote() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_daily_note") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all templates from `.cortex/templates/`.
 */
async listTemplates() : Promise<Result<TemplateInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_templates") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new note from a named template. Returns the relative path of the created note.
 */
async createFromTemplate(templateName: string, title: string, folder: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_from_template", { templateName, title, folder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start recording audio via the voice pipeline.
 */
async voiceStartRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_start_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop recording and return the path to the saved WAV file.
 */
async voiceStopRecording() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_stop_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel the current recording without saving.
 */
async voiceCancelRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_cancel_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List available audio input devices.
 */
async voiceGetDevices() : Promise<Result<AudioDeviceInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_get_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if the voice pipeline is currently recording.
 */
async voiceIsRecording() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("voice_is_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AudioDeviceInfo = { name: string; is_default: boolean }
/**
 * A backlink: another note that links to the current note.
 */
export type Backlink = { 
/**
 * Relative path of the note containing the link.
 */
source_path: string; 
/**
 * Title of that note.
 */
source_title: string; 
/**
 * The line of text containing the link (for context preview).
 */
context: string; 
/**
 * Line number in the source note.
 */
line: number }
/**
 * Parsed YAML frontmatter from a note.
 */
export type Frontmatter = { title: string | null; tags: string[]; aliases: string[]; created: string | null; modified: string | null; 
/**
 * Extra frontmatter fields serialized as JSON strings.
 */
extra: Partial<{ [key in string]: string }> }
/**
 * Full graph data for visualization.
 */
export type GraphData = { nodes: GraphNode[]; edges: GraphEdge[] }
/**
 * An edge in the knowledge graph.
 */
export type GraphEdge = { 
/**
 * Source note path.
 */
source: string; 
/**
 * Target note path.
 */
target: string }
/**
 * A node in the knowledge graph.
 */
export type GraphNode = { 
/**
 * Note path (unique identifier).
 */
id: string; 
/**
 * Note title (display label).
 */
label: string; 
/**
 * Number of connections (forward + backward links).
 */
weight: number }
/**
 * Data returned to the frontend when reading a note.
 */
export type NoteData = { content: string; frontmatter: Frontmatter | null }
/**
 * A single search result returned from a full-text query.
 */
export type SearchResult = { 
/**
 * Relative file path within the vault.
 */
path: string; 
/**
 * Note title (derived from filename).
 */
title: string; 
/**
 * Matching text snippet with surrounding context.
 */
snippet: string; 
/**
 * Relevance score from the search engine.
 */
score: number }
/**
 * Tag information with occurrence count.
 */
export type TagInfo = { 
/**
 * Tag name without the leading `#`.
 */
name: string; 
/**
 * How many notes have this tag.
 */
count: number }
/**
 * Metadata about a template file.
 */
export type TemplateInfo = { name: string; preview: string }
/**
 * Represents a file or directory inside the vault.
 */
export type VaultFile = { 
/**
 * Relative path from vault root.
 */
path: string; 
/**
 * Filename or directory name.
 */
name: string; 
/**
 * Whether this entry is a directory.
 */
is_dir: boolean; 
/**
 * Last modified time as unix timestamp.
 */
modified: number; 
/**
 * Children entries (for directories).
 */
children: VaultFile[] | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
